<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class KeluhansSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('keluhans')->insert([[
            // "id_keluhan" => 1,
            "nomor_keluhan" => "#T2023020133761",
            "sumber_id" => 1,
            "detail_sumber" => "08888882234",
            "pop_id" => 1,
            "id_pelanggan" => "UNREGISTERED",
            "nama_pelanggan" => "AGUS SUSANTO",
            "nama_pelapor" => "Agus",
            "nomor_pelapor" => "08888882234",
            "kategori_pelanggan" => "UNREGISTERED",
            "keluhan" => "Koneksi lambat",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => null,
            "rfo_keluhan_id" => 2,
            "deleted_at" => null,
            "created_at" => "2023-02-01T11:14:47.000Z",
            "updated_at" => "2023-02-01T11:55:19.000Z",
        ],
        [
            // "id_keluhan" => 2,
            "nomor_keluhan" => "#T2023020122987",
            "sumber_id" => 1,
            "detail_sumber" => "087786765667",
            "pop_id" => 1,
            "id_pelanggan" => "100004422",
            "nama_pelanggan" => "MAULANA IBRAHIM",
            "nama_pelapor" => "Maul",
            "nomor_pelapor" => "087786765667",
            "kategori_pelanggan" => "REGISTERED",
            "keluhan" => "Koneksi putus-putus sejak seminggu yang lalu",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => null,
            "rfo_keluhan_id" => 4,
            "deleted_at" => null,
            "created_at" => "2023-02-01T11:17:12.000Z",
            "updated_at" => "2023-02-01T12:14:57.000Z",
        ],
        [
            // "id_keluhan" => 3,
            "nomor_keluhan" => "#T2023020116957",
            "sumber_id" => 8,
            "detail_sumber" => "@kittendust",
            "pop_id" => 1,
            "id_pelanggan" => "100005524",
            "nama_pelanggan" => "FATHIA IZZATI",
            "nama_pelapor" => "Chia",
            "nomor_pelapor" => "08556434678",
            "kategori_pelanggan" => "REGISTERED",
            "keluhan" => "Koneksi terputus setelah ada petir semalam",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => null,
            "rfo_keluhan_id" => 3,
            "deleted_at" => null,
            "created_at" => "2023-02-01T11:19:47.000Z",
            "updated_at" => "2023-02-01T12:02:47.000Z",
        ],
        [
            // "id_keluhan" => 4,
            "nomor_keluhan" => "#T2023020156615",
            "sumber_id" => 3,
            "detail_sumber" => "baskara.hindia@gmail.com",
            "pop_id" => 1,
            "id_pelanggan" => "UNREGISTERED",
            "nama_pelanggan" => "BASKARA PUTRA",
            "nama_pelapor" => "Baskara",
            "nomor_pelapor" => "08998635364",
            "kategori_pelanggan" => "UNREGISTERED",
            "keluhan" => "Ping saya  tinggi saat digunakan untuk bermain game Mobile Legend. \n Mohon dicekkan",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => 1,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T11:24:23.000Z",
            "updated_at" => "2023-02-01T12:58:37.000Z"
        ],
        [
            // "id_keluhan" => 5,
            "nomor_keluhan" => "#T2023020152261",
            "sumber_id" => 8,
            "detail_sumber" => "@ginagini",
            "pop_id" => 1,
            "id_pelanggan" => "100008998",
            "nama_pelanggan" => "KUPIKU COFFEE",
            "nama_pelapor" => "Gina",
            "nomor_pelapor" => "08665434363",
            "kategori_pelanggan" => "REGISTERED",
            "keluhan" => "mas koneksi nya lambat banget untuk game-game \n tolong dicekkan ya",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => 1,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T12:05:54.000Z",
            "updated_at" => "2023-02-01T12:12:35.000Z"
        ],
        [
            // "id_keluhan" => 6,
            "nomor_keluhan" => "#T2023020156208",
            "sumber_id" => 1,
            "detail_sumber" => "089976554321",
            "pop_id" => 1,
            "id_pelanggan" => "UNREGISTERED",
            "nama_pelanggan" => "COUVEE COFFEE",
            "nama_pelapor" => "Intan",
            "nomor_pelapor" => "089976554321",
            "kategori_pelanggan" => "UNREGISTERED",
            "keluhan" => "Dilaporkan modem dalam keadaan loss",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => 2,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T12:17:08.000Z",
            "updated_at" => "2023-02-01T12:41:13.000Z"
        ],
        [
            // "id_keluhan" => 7,
            "nomor_keluhan" => "#T2023020158727",
            "sumber_id" => 8,
            "detail_sumber" => "@kopikopiapayangfore",
            "pop_id" => 1,
            "id_pelanggan" => "UNREGISTERED",
            "nama_pelanggan" => "FORE COFFEE",
            "nama_pelapor" => "Fira",
            "nomor_pelapor" => "0877654432",
            "kategori_pelanggan" => "UNREGISTERED",
            "keluhan" => "Mas ini kok modemnya tiba2 error ya",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => 2,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T12:18:40.000Z",
            "updated_at" => "2023-02-01T12:41:06.000Z"
        ],
        [
            // "id_keluhan" => 8,
            "nomor_keluhan" => "#T2023020111790",
            "sumber_id" => 3,
            "detail_sumber" => "alex.AM@gmail.com",
            "pop_id" => 1,
            "id_pelanggan" => "100002334",
            "nama_pelanggan" => "M ALEX TURNER",
            "nama_pelapor" => "Alex",
            "nomor_pelapor" => "089965443212",
            "kategori_pelanggan" => "REGISTERED",
            "keluhan" => "Hello Support, \n I got problem with my connection \n can u please check it?",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => 2,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T12:21:14.000Z",
            "updated_at" => "2023-02-01T12:40:46.000Z"
        ],
        [
            // "id_keluhan" => 9,
            "nomor_keluhan" => "#T2023020131963",
            "sumber_id" => 9,
            "detail_sumber" => "@jajangbukanmyon",
            "pop_id" => 1,
            "id_pelanggan" => "UNREGISTERED",
            "nama_pelanggan" => "JAJANG SUSENO",
            "nama_pelapor" => "Jajang",
            "nomor_pelapor" => "08996543321",
            "kategori_pelanggan" => "UNREGISTERED",
            "keluhan" => "mazz kok koneksinya parah sih ini",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => 2,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T12:24:39.000Z",
            "updated_at" => "2023-02-01T12:40:38.000Z"
        ],
        [
            // "id_keluhan" => 10,
            "nomor_keluhan" => "#T2023020151612",
            "sumber_id" => 1,
            "detail_sumber" => "087654432678",
            "pop_id" => 1,
            "id_pelanggan" => "100005674",
            "nama_pelanggan" => "FAJAR PURNAMA",
            "nama_pelapor" => "Fajar",
            "nomor_pelapor" => "087654432678",
            "kategori_pelanggan" => "REGISTERED",
            "keluhan" => "Dilaporkan modem dalam keadaan loss",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => 2,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T12:27:56.000Z",
            "updated_at" => "2023-02-01T12:40:27.000Z"
        ],
        [
            // "id_keluhan" => 11,
            "nomor_keluhan" => "#T2023020151586",
            "sumber_id" => 3,
            "detail_sumber" => "your.eby@gmail.com",
            "pop_id" => 1,
            "id_pelanggan" => "UNREGISTERED",
            "nama_pelanggan" => "ABIGAIL",
            "nama_pelapor" => "Eby",
            "nomor_pelapor" => "087866543",
            "kategori_pelanggan" => "UNREGISTERED",
            "keluhan" => "ngadat lagi koneksinya mas",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => null,
            "rfo_keluhan_id" => 6,
            "deleted_at" => null,
            "created_at" => "2023-02-01T12:44:38.000Z",
            "updated_at" => "2023-02-01T12:57:07.000Z"
        ],
        [
            // "id_keluhan" => 12,
            "nomor_keluhan" => "#T2023020185978",
            "sumber_id" => 2,
            "detail_sumber" => "+62 879-778-909",
            "pop_id" => 2,
            "id_pelanggan" => "200008976",
            "nama_pelanggan" => "GIBRAN PANGAREP",
            "nama_pelapor" => "Gibran",
            "nomor_pelapor" => "0879778909",
            "kategori_pelanggan" => "REGISTERED",
            "keluhan" => "ngapunten mas \n niki kenapa koneksinya down ya \n saya lagi zoom meeting terganggu",
            "sentimen_analisis" => "Positive",
            "status" => "closed",
            "user_id" => 1,
            "rfo_gangguan_id" => null,
            "rfo_keluhan_id" => 5,
            "deleted_at" => null,
            "created_at" => "2023-02-01T12:47:25.000Z",
            "updated_at" => "2023-02-01T12:50:25.000Z"
        ],
        [
            // "id_keluhan" => 13,
            "nomor_keluhan" => "#T2023020180840",
            "sumber_id" => 1,
            "detail_sumber" => "089976554321",
            "pop_id" => 1,
            "id_pelanggan" => "UNREGISTERED",
            "nama_pelanggan" => "MUHAMMAD AFFANDI",
            "nama_pelapor" => "Affan",
            "nomor_pelapor" => "089976554321",
            "kategori_pelanggan" => "UNREGISTERED",
            "keluhan" => "koneksi lag parah",
            "sentimen_analisis" => "Positive",
            "status" => "open",
            "user_id" => 1,
            "rfo_gangguan_id" => null,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T13:03:25.000Z",
            "updated_at" => "2023-02-01T13:03:25.000Z"
        ],
        [
            // "id_keluhan" => 14,
            "nomor_keluhan" => "#T2023020151792",
            "sumber_id" => 1,
            "detail_sumber" => "08769859876",
            "pop_id" => 1,
            "id_pelanggan" => "UNREGISTERED",
            "nama_pelanggan" => "SHINTA WIDY",
            "nama_pelapor" => "Shinta",
            "nomor_pelapor" => "0876098712",
            "kategori_pelanggan" => "UNREGISTERED",
            "keluhan" => "Terkendala untuk streaming tiktok",
            "sentimen_analisis" => "Positive",
            "status" => "open",
            "user_id" => 1,
            "rfo_gangguan_id" => null,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T13:05:27.000Z",
            "updated_at" => "2023-02-01T13:05:27.000Z"
        ],
        [
            // "id_keluhan" => 15,
            "nomor_keluhan" => "#T2023020174732",
            "sumber_id" => 8,
            "detail_sumber" => "@rahajengjeng",
            "pop_id" => 1,
            "id_pelanggan" => "100002329",
            "nama_pelanggan" => "RAHAJENG ",
            "nama_pelapor" => "Ajeng",
            "nomor_pelapor" => "087769854322",
            "kategori_pelanggan" => "REGISTERED",
            "keluhan" => "modem saya loss kak",
            "sentimen_analisis" => "Positive",
            "status" => "open",
            "user_id" => 1,
            "rfo_gangguan_id" => null,
            "rfo_keluhan_id" => null,
            "deleted_at" => null,
            "created_at" => "2023-02-01T13:10:08.000Z",
            "updated_at" => "2023-02-01T13:10:08.000Z"
        ]
    ]);
    }
}
